version: 2

sources:
  - name: job_market
    database: postgres
    schema: public
    tables:
      - name: raw_crypto_jobs
        description: "Bảng chứa dữ liệu việc làm thô cào từ các trang tuyển dụng"
