name: Job Market Pipeline

on:
  push:
  schedule:
    # Chạy tự động lúc 00:00 mỗi ngày (giờ UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Cho phép bro bấm nút "Run" thủ công để test

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: job-market-pipeline
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dbt-postgres

      - name: Run Crawlers
        env:
          DB_CONN: ${{ secrets.DB_CONN }}
          # Đã xóa ITVIEC_COOKIE vì không xài tới nữa
        run: |
          # Chỉ giữ lại duy nhất ông kẹ LinkedIn
          python crawler/linkedin_crawler.py

      - name: Run dbt
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASS: ${{ secrets.SUPABASE_PASSWORD }}
        run: |
          dbt run --project-dir dbt_job_market --profiles-dir dbt_job_market --target dev
          
      - name: Send Discord Alerts
        env:
          DB_CONN: ${{ secrets.DB_CONN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python alert_bot.py